{
  "title": "Sample Puzzle",
  "by": "By Line",
  "clues": [
    { "d":"A", "n":6, "x":1, "y":1, "a":"REPEATS", "c":"Shows you've seen" },
    { "d":"A", "n":7, "x":9, "y":1, "a":"NINES", "c":"Eights aren't enough" },
    { "d":"A", "n":9, "x":0, "y":3, "a":"DIAL", "c":"Don't touch that __" },
    { "d":"A", "n":10, "x":5, "y":3, "a":"ASTRONOMER", "c":"Starstruck scientist" },
    { "d":"A", "n":11, "x":0, "y":5, "a":"WEIGHING", "c":"Measuring heaviness" },
    { "d":"A", "n":13, "x":9, "y":5, "a":"COUSIN", "c":"Maybe you can marry" },
    { "d":"A", "n":15, "x":0, "y":7, "a":"JAZZ", "c":"American music" },
    { "d":"A", "n":17, "x":5, "y":7, "a":"BOATS", "c":"Marina sights" },
    { "d":"A", "n":18, "x":11, "y":7, "a":"EASE", "c":"Let out" },
    { "d":"A", "n":19, "x":0, "y":9, "a":"PURSES", "c":"Sums of money" },
    { "d":"A", "n":20, "x":7, "y":9, "a":"POSTPONE", "c":"Give a rain check" },
    { "d":"A", "n":23, "x":0, "y":11, "a":"RIDICULOUS", "c":"Cockamamy" },
    { "d":"A", "n":26, "x":11, "y":11, "a":"CAGE", "c":"Hamster's home" },
    { "d":"A", "n":27, "x":1, "y":13, "a":"GHOST", "c":"Father & son, three's a crowd" },
    { "d":"A", "n":28, "x":7, "y":13, "a":"ELEMENT", "c":"Substance like no other" },
    { "d":"D", "n":1, "x":3, "y":0, "a":"APOLOGIZES", "c":"Makes amends" },
    { "d":"D", "n":2, "x":5, "y":0, "a":"HAWAII", "c":"Barack's home " },
    { "d":"D", "n":3, "x":7, "y":0, "a":"ISNT", "c":"__ it romantic?" },
    { "d":"D", "n":4, "x":9, "y":0, "a":"ENFORCES", "c":"Keeps lawfull" },
    { "d":"D", "n":5, "x":11, "y":0, "a":"ONTO", "c":"I'm __ you!" },
    { "d":"D", "n":6, "x":1, "y":1, "a":"RAISE", "c":"Bring up" },
    { "d":"D", "n":8, "x":13, "y":1, "a":"SPECIES", "c":"Variety" },
    { "d":"D", "n":12, "x":7, "y":5, "a":"GRASP", "c":"Hold" },
    { "d":"D", "n":14, "x":11, "y":5, "a":"UNEXPECTED", "c":"Abrupt" },
    { "d":"D", "n":16, "x":1, "y":7, "a":"AMUSING", "c":"Gladdening" },
    { "d":"D", "n":17, "x":5, "y":7, "a":"BISCUITS", "c":"Go with gravy" },
    { "d":"D", "n":21, "x":9, "y":9, "a":"SISTER", "c":"Nun" },
    { "d":"D", "n":22, "x":13, "y":9, "a":"NIGHT", "c":"Dusk to dawn" },
    { "d":"D", "n":24, "x":3, "y":11, "a":"IRON", "c":"Pumping __" },
    { "d":"D", "n":25, "x":7, "y":11, "a":"OVER", "c":"Game __" }
  ]
}
